#!/usr/bin/env sh

python3 -m venv virtualenv venv

echo
echo "Activate virtualenv with this command:"
echo
echo "  $ source virtualenv/bin/activate"
echo
echo "Once you've activated the virtualenv, install Django & Selenium:"
echo
echo '  $ pip install "django<1.12" "selenium<4"'
echo
echo "Deactivate virtualenv with this command:"
echo
echo "  $ deactivate"
echo
